export {default as Home} from './home/HomeLayout'
export {default as Details} from './productDetails/ProductDetailsLayout'
export {default as AllItems} from './allItems/AllItemsLayout'
export {default as Cart} from './cart/CartLayout'
export {default as NotFound} from './notFound/NotFoundLayout'